import { copyKeys } from "../../utils";
// eslint-disable-next-line node/no-missing-import
import { Etablissement } from "frentreprise";

class DireccteEtablissement extends Etablissement {
  export() {
    return {
      ...copyKeys(
        this,
        [
          "siege_social",
          "siret",
          "enseigne",
          "categorie_etablissement",
          "adresse",
          "adresse_composant",
          "departement",
          "region",
          "code_region",
          "date_creation",
          "etat_etablissement",
          "etat_etablissement_libelle",
          "date_fin",
          "date_dernier_traitement_etablissement",
          "date_debut_activite_economique",
          "diffusable_commercialement",
          "modalite_activite",
          "marchand",
          "etablissement_employeur",
          "tranche_effectif_insee",
          "annee_tranche_effectif_insee",
          "dsnEffectif",
          "dernier_effectif_physique",
          "date_dernier_effectif_physique",
          "source_dernier_effectif_physique",
          "effectifMensuelEtp",
          "unite_controle_competente",
          "idcc",
          "agefiph_derniere_annee_conformite_connue",
          "donnees_ecofi",
          "eti_pepite",
          "filiere_strategique",
          "structure_insertion_activite_economique",
          "structure_insertion_activite_economique_types",
          "activite_partielle",
          "pse",
          "lice",
          "rcc",
          "interactions_3E_SEER",
          "interactions_3E_SRC",
          "interactions_T",
          "interactions_C",
          "association",
          "document_association",
          "predecesseur",
          "successeur",
          "caractere_saisonnier",
          "caractere_auxiliaire",
          "accords",
          "pole_competitivite",
          "ea",
          "prime_embauche_pme",
          "naf",
          "libelle_naf",
          "nom_commercial",
          "nom",
          "prenom",
          "agrements_iae",
          "contrat_aide",
          "contrat_aide_alternance_n1",
          "contrat_aide_salaries_n1",
          "contrat_aide_embauches_n1",
          "apprentissage",
          "_dataSources",
          "_success",
        ],
        null
      ),
    };
  }
}

export default DireccteEtablissement;
