apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1
  name: azure-fce-volume
spec:
  encryptedData:
    azurestorageaccountname: AgCCbwpo4RYj+KYJfUArfcjxmVRuhUhciMTfXvpHs0ui37ivl1YDCmXmW3ylRqUx8qaw+DLL+PQPgyEzmdDVCNJ2hSky5x2yajfL0MmhHgkepoQSK1IELz3JHDKM+ShzSlRS0UiQnjDTysSf8xSFI/QUqcWQBOlJAEQCz8C1awiQz7aYdihL+bpyxH/uamgwRN3GWXMSMh05NjHo2zUZO6DfJ2qJYrzcy75s9+0wa8mwH6hA2kV89Aij9vrGm20DFj1iCe52FDUD6eqHcWe8vfz7vvWBPxC1lb6wp86jezxqdWWjieLn+imtVTTEhndInoyzzvWGtlU7ZIGcR7XqHhrwcxlkiT5LrG9RqGqyHIiJMGF9VpW3IlqdPJU1D/KFBDdOijB4U0aFsOBVaIxXFjtPhP8QO2huAtSgFcwNV1f1pRkhJzpMiY9mU257nDQyNRZInpGFAoV2FK4Nquuar8yGi3BsDk9LpqKejTNjYEHl/I1FitpwqIdttOYpx3JVKP29rZtjS9c9e5O2xgwDS3Q21GhOffKhHX+V+prDXA4I+BUpXkW+vNwB9NTt/WYyCG1hzDcPkHTuZyhNV0at7mfWec9zoZiUBw8m+Xrw64H88pIEJXM1E7BNoZfF/oqRdf46pAidcWMp2uPItVv6HEfa5JZGAL7Qtwm31vFZdGKdgWCF9PeMYIL5UdI2WAqsLj2np9eHXZPA
    azurestorageaccountkey: AgAlN7lsY17kIsFsYZ9CJ3wPb35eAM5s20oztZ+VTQNN3+ABCJT1PJozVZPo1btdElsGV3RAA6apU4A3L33fZZ6MTdhNY3cuTcHD9DZp7JjEWRtGRKImDb7HMDeoYSXfGjTSh6iThChDk9rvH+9M5SRZfGHIoVtKgr4d2FChOVylNmrwvX3hUBflhrvvKWHX+VIbvkRpr+1TeQtaPJn2JoaigDY9YzKviZ1nhER/oNqxRn3hpzAKFrwnLDKqzISwTfG8nTh6eUCfJgLxF6+4zVQtPBZCebWWPrxcqCar3zoLHvnZlkN3WkKk8BPeiAn/VX921fUdJdhecUIZCi6kTdv3vw8nLf5pMONpWvjsUYwqpr7spd/Pcua/vgAHUOw9V11pds837QPA5tcThfG5n4wiX/xeRw9N+jZqs3sFcuEqJQ0gqkmE1uisyMViOjn2z9UudtccAWL+Ll/KNbr8I6Fwy2SW0eUQh/aL0lafOyS/9fG6qAicg8nDI7C/bfKcS59y3S/p/kWFBz5GDCnjGJa8ezTkyUy8tIMe/gCs2RFvj6zaeOFTguFeRiSeFN9uOF9UooMcR+cPBSgtsAWGzmvZjYq0YYHTLacLTA1XqwOwVbDV4IgXAb/OeRuCEOPd+JunRpztjEqggD0U99qIB8egYLoQOBUxocr2ZM5xNDkMb8h4q5EpORxlpervPKPmcivx03qMpjPCsiBSQQB4Z0TK2fhmv1Kar94xMM6Aiy3svHzBi0Xo74fsu3pFbk85S1w4342wcoyAzWGVJwt4z1xRJPi6yewbHDDD1Pyu6Z4/CM6RqY5UhRKY
  template:
    metadata:
      annotations: *a1
      name: azure-fce-volume
    type: Opaque

