kind: ConfigMap
apiVersion: v1
metadata:
  name: n8n-env
data:
  DB_TYPE: postgresdb
  N8N_PORT: "5678"
  N8N_BASIC_AUTH_ACTIVE: "true"
  PG_PORT: "5432"
  PG_SSL: "true"
  GENERIC_TIMEZONE: "Europe/Paris"
  AZURE_SHARE_NAME: "bce"

  MINIO_BCE_ENDPOINT: "bce-prod-minio.cegedim.cloud"
  MINIO_BCE_PORT: "443"
  MINIO_BCE_SSL: "true"

  ELASTIC_SEARCH_URL: "https://recherche-entreprises-prod2.es.francecentral.azure.elastic-cloud.com"

  SMTP_URL: "smtp.tipimail.com"
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
