kind: ConfigMap
apiVersion: v1
metadata:
  name: server-env
data:
  PROD: "true"
  CLIENT_BASE_URL: client-url
  PORT: "3000"
  MAGIC_KEY_EXPIRE: "3600"
  #Appsearch
  JWT_APPSEARCH_ADDRRESS: https://appsearch-fce-prod.fabrique.social.gouv.fr/api/as/v1/
  JWT_APPSEARCH_ENGINE_NAME: fce
  JWT_ELASTIC_CLIENT_ADDRESS: http://elasticsearch:9200/

  #MATOMO
  MATOMO_ID_SITE: "8"
  MATOMO_URL: https://matomo.fabrique.social.gouv.fr

  #LOGIN
  JWT_EXPIRE_BEFORE: "1634130400"

  #Strapi
  STRAPI_URL: "http://strapi:80"

  #ELASTIC SEARCH
  ELASTIC_URL: "https://recherche-entreprises-prod2.es.francecentral.azure.elastic-cloud.com"
  ELASTIC_INDEX: "fce-search"

  #CACHING
  CACHE_TYPE: "redis"
  REDIS_URL: "redis://redis:80"

  TZ: "UTC"
