apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: pgadmin-servers
spec:
  inputResources:
  - name: app
    ref:
      apiVersion: v1
      kind: Secret
      name: pg-app
  template:
    data:
      servers: |
      {
        "Servers": {
          "1": {
            "Name": "$(.app.metadata.name)",
            "Group": "Servers",
            "Host": "$(.app.data.PGHOST)",
            "Port": $(.app.data.PGPORT),
            "MaintenanceDB": "postgres",
            "Username": "$(.app.data.PGUSER)",
            "SSLMode": "prefer",
            "PassFile": "/var/lib/pgadmin/$(.app.metadata.name)"
          }
        }
      }

