apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1
  name: hasura-env
  namespace: fce
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgA33lYF9V4DKEBgDyqKwxCygNXJnHYy6IDGx7KE8mSsbeFDzH6RPUEcM/NVe5xY7+CAnPyT4NHrqmym51LjJDUuFzYHtoC1EMJrQdxpfDCzXGPOUI50vStveAM5PvTS/ozS8TJo9tGjJDkJ1g9u3hi6CBK7dZj/1wOkphbAzGy0Il8V6sB5QCZmNQetytUIYa4L6JSJsuQKr2V1tH+W4SrjQXyjiEOHorWXzIOn8GTaBc3WZ/w7qvED5Nsn+aF9ULe1MBu/44Z5h57Cjc3Y4RQZmJ2FgXRQRcFHEoUhQTSmI3ut10yl+SiADReVDbdv1u7VI6UCZzJ/aYCmqBRFI2jrrQJgCCuCOjEw6Xjhf2s9LQbu/GrmLzFd3GYhlz5o7N/PClOgtAFGfcniZNa3ALVwueV1YZ/j2Si/jvHn58pfqD42eXSihrXozJq6MPnh8F46vNjbkSTXAZEnygVoI0Gdu+PLllVU5gTqYFWQyfzwlc9ttNWEsMn1WO6JizWq6CC7ET+UeXr5vp/VgBIz+aaDlrs/IonpXbSCfKbA903lpWNUjLAHleEI/uTySWfUcqwYwsEMiDxtzvoGOOQJzuzSz/pWbjxWyecCxpBFow6Ljxoy39wWOd0FtkXPLM+X7B2UrSgdYrCoYEYcuvBPa/pmlOzQGpwiOt139kDJ90Ho/muUDrCxONg3qs7dZZ45JOVh8/3lnp5Ql4SopKZDM7T/is0tDalUpiUQ1jnAuUKT3A==
    HASURA_GRAPHQL_DATABASE_URL: AgAo8t30EGnJszRJy1UxZdyyBWXq007bxTOChzG3nzoCwvmU+1JVo6JT4IMOlI2CCYebHNk6CZahTiIJisFNj0TlaXDChYqKWImBinPBZqr1sv1zXnACJHSW7G543kunRorPHfyn7ZVIusd8XgFlcK/69GajEtzFVka6qUnWtPEmjQhtIpnSYeJMyGJnE1Y4O2/yTYl11opPml1P7lbqk5wW77ed5ivZQP7UUp4Whbo4ZM61r/ZV1nOyGZ9PzKwSbaftTAhXi0sf1Dw2/UUT5sYohWwlM37qnPBsffuAg9x8XPhAD6fRGCrJ41Fk3Hu/9o7wcQr9xfiJm0Jx7nwYpsJJ0tk4x4NrI/Vt74yetEWdJXKare91hntQBRDNt/YTpGlRBBwbkU5VhTQmH644DCyBgb2ZKOgIOo4k1fFRSVGsKrioJW/VgRMWD1VaGO4eflvK8GR6QINMyjBZV9LdkIGpvnYW44+xaXv+CmFOpzwprBk+PbpMWpO/MSMrSKhxLxAHdNzcQXJIA2hUgf8KscbYow8KF7sQAyJV5Wg3Mo0C5XJKR7GHJXirRQVwbknDXu3/QwrEikkae1sprE8ZYiV/rmF4Yi2orWpSYCpfYURF8yrXE9bFM5M94XEcNMnKvfJE9ljrF1woEgTAzfUzMsV4dhHEr73TH+JEIlptNgJCWZTRRjSTEipRRhwgedPLe3QTkFHASvdWon8lUOVA6vDCnl+Pn2LGlXRNPfdooRBw2tTbYjHk+TiEFc2loAZ2wpeB2Hzmlncwhf0sckRQGY41s89Em0p/EatS8aOXkXpliwYFa6QSmYZF54XISuXJqUVoOjnn

  template:
    metadata:
      annotations: *a1
      name: hasura-env
    type: Opaque

