apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1
  name: hasura-env
  namespace: fce
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgA33lYF9V4DKEBgDyqKwxCygNXJnHYy6IDGx7KE8mSsbeFDzH6RPUEcM/NVe5xY7+CAnPyT4NHrqmym51LjJDUuFzYHtoC1EMJrQdxpfDCzXGPOUI50vStveAM5PvTS/ozS8TJo9tGjJDkJ1g9u3hi6CBK7dZj/1wOkphbAzGy0Il8V6sB5QCZmNQetytUIYa4L6JSJsuQKr2V1tH+W4SrjQXyjiEOHorWXzIOn8GTaBc3WZ/w7qvED5Nsn+aF9ULe1MBu/44Z5h57Cjc3Y4RQZmJ2FgXRQRcFHEoUhQTSmI3ut10yl+SiADReVDbdv1u7VI6UCZzJ/aYCmqBRFI2jrrQJgCCuCOjEw6Xjhf2s9LQbu/GrmLzFd3GYhlz5o7N/PClOgtAFGfcniZNa3ALVwueV1YZ/j2Si/jvHn58pfqD42eXSihrXozJq6MPnh8F46vNjbkSTXAZEnygVoI0Gdu+PLllVU5gTqYFWQyfzwlc9ttNWEsMn1WO6JizWq6CC7ET+UeXr5vp/VgBIz+aaDlrs/IonpXbSCfKbA903lpWNUjLAHleEI/uTySWfUcqwYwsEMiDxtzvoGOOQJzuzSz/pWbjxWyecCxpBFow6Ljxoy39wWOd0FtkXPLM+X7B2UrSgdYrCoYEYcuvBPa/pmlOzQGpwiOt139kDJ90Ho/muUDrCxONg3qs7dZZ45JOVh8/3lnp5Ql4SopKZDM7T/is0tDalUpiUQ1jnAuUKT3A==
    HASURA_GRAPHQL_DATABASE_URL: AgCo1ctKnzZa9B2fUoOFcx7OuL+ZRdBQFMseTJGfcu2gonAGIhV4x7HKlbKSKDrHVAxbkGRuw+d5nGuQwAPTcKngIZYdq9V1HeR9vfvRjAtOkQCUECoxzDsqH4Wgpx4eDAMdZtJdpBHCEi2HBK8V+UygNTqhRK0+EMk7h9EQ4ZfiEr8dmexovpTz+/wh5Xa4B0gO1aU+vdp1XOuTR7NxTCHVzDvIobDMGUrFq57JsB1H2pMDq0G8GHQJJESGO6ijOnh9iPTM4MIK6O6VKrbEPGBGLf1kqSw7NfE8Jke7PclHMtdTg9nYydJaWrJmcYbE/drL4w8iZJxZN5/FNvFkKMJ1fwEERHLPKfvPUcfrwWPPWCmYPelSt19n3Tr3uLinNJQfYm5qk5HukOdY4Eh/6mxE+TIWDZr4SJeq9QdHq93xP/6H1w9mSDEwsQFjJcVRf9vmsJJzegXjOZ5sZRFMkv1Wb920n8sCubv+iMn6hYWBBSwZ/GHdjIwARIGqPYoxQL+6m/f25VNmm/Vyq4lIZGvmAC/PXcjA76b1+XJmUh5JUc9W1n0mkD9VBqe0Xr40WhJqETCQiaRvl25xDLw8LvHEPaeoqNp2Turw2BvqlxeqL6ly22TrXlzK4Ab9NE66HVhYe1gtT6MOYVGzkhg9M+Mgrj4/WkIeeOn8ZxPkSirLNZklTJ4DLao9WPxCJHKhBSE4DflPIcHfv1Q6OgKLrx4InywmClXUIzh9yilWtu5DVVrJMZT+Kwl72CBeD5EtcGxkcFd1F9qcODPTR3VpB6xQJizWD5QexCLeAf/TyLz5IZCc9kZ8Ys6ntmLckm+egKJWJf/gz/lwRQ==

  template:
    metadata:
      annotations: *a1
      name: hasura-env
    type: Opaque

