apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: azure-fce-volume
spec:
  encryptedData:
    azurestorageaccountname: AgCDKbl6Aon8etQpc+1lXi2pefHBkAUv3mWNgyofwpcDLT+L5REHvMj+XwO/CAJb+8E2WbeQbRPBo9G4RQo8ZUzWT3+Xi7YzB+XD6ckPL0ccly5oCgM7ishON6C+ybdSMwEF2c06Nv7K+2b3SZ36I9mnTilOQU4NVkFmCGivKj3nVAMBxkCz88WVUTMwtd6bKkExkGTL14yK8CHk/bWlg72c25ujGvklg5ffZddcokxEgUfLdJXYQ4/oosXI7HnpKCy6NH/YAU6jE3fYeXo/7MCsBN2tHdWEdqVu4wMs3ymuYPkSGkLHJfMkbvTrcYvGxjMB0yU8bC3lFFarcJRIqYS1AuS3dTRUbxkJo472OUHIAZOIVMA4wpdI/WOOwCBGXTKz7rgxdKRUALJBhN+atYSa7oynh29se0U+9q1HMjTO3Dr6JFm2D9txulxddbwXZf/HLoCZdyG0K1/IoV3ImXJhMULKhiOPpghhNTHRu/6upCVhEtkn0VlVI9bAbEOUIemHDLBZP3TQQKM8zYI9FsWcJC2zLNLftJ5YHQl9+5hWXyRDGMDJau9EfPG7hXEO7kyhABpaIMhjyqhLCoUAP6dc03yjA1loO6MJA/Z82Rb20RMuqvYh/8WFi4feqqJHMBkzUJwj3fugGUc6lDrY9ieikNJEOY9vW4xvZ0pUF11XVM2ekvQLGNMUDDHecjVybKY3c4bszFA=
    azurestorageaccountkey: AgAVSbINE67jQ7Ubw4lHfxpN7PTIHtLEfp2MxUTl5DOtRbggN8yNPt8ChCGU/6lNAja+TV5BbNFZp78joFDoXbxvGpAssFEDUXHsmNUX03OL1oj0Z7rQMeF7EnjakelTBtsFAL3aN1AsB/cDNl9gbDAIQCcwCmswhndo3hCsOjJzuVxK1jOf53ZN5EvLFXEuGspDSxURBysoVzl57R7ahA6BsZ2wEskbsF4R9eYlb8oaya/a1wcNLzl1Ee11nT4yFll5V8OlRYQOqnseKGGkzFazQ0WkxljAR3ROWSl335yuWfnmwJdL2U+xjXj/8CQf77z31w5kNgvhBT7mUWPrfYtAfgfULIFtlRArIPo050rZx3l8LkfP6ASW3wxGE3T1recKr0cKmrULOYHGKqnub3/RuJKyjz5VVBbfli83BOhv+fty8cZxBWDNKDY4Asrp7V6uSC8zyGQeNrrVIR8WjaqXMatQUmnhg4bcGrI3zj2wEONv/+knh/Akooe8vDU/gtgMT6IM7NiRQqL8JKdjH1Mi5wDIPUHMks2ZuFa+DdYd7aqBk668VfBnR2auS26Ek7VjLNGMCmDrb2orjNzLiBMXBEZcKUH4MI+96yh4PxOEuKswgmQOXdhIaJB7LudVlRIfma+05vSDUMJznpbHYfuJ9rTm9uxnu7oGsMIxyDnVfhaH3Ke56QQgWJAOhwpdLqnZJ+rCZGZ4JLroGPO4/uSEajp7JSjtSPvRKRLSRO2tigeK+hhXa7Hhp3aEmcSek+AUyNZJEFwqvAJQFGTOZHFO6sCzKItfafvItPczIHlbURxEozgpKHuN
  template:
    metadata:
      annotations: *a1
      name: azure-fce-volume
    type: Opaque

