export const SET_CURRENT_ENTERPRISE = "SET_CURRENT_ENTERPRISE";

export const SET_SOURCES = "SET_SOURCES";

export const RESET_STORE = "RESET_STORE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_FILTERS = "SET_SEARCH_FILTERS";
export const SET_SEARCH_SORT = "SET_SEARCH_SORT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_IS_LOADING = "SET_SEARCH_IS_LOADING";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
export const RESET_SEARCH = "RESET_SEARCH";
