export const SET_CURRENT_ENTERPRISE = "SET_CURRENT_ENTERPRISE";
export const SET_START_LOADING_ENTERPRISE = "SET_START_LOADING_ENTERPRISE";
export const SET_SOURCE_COMPLETED_ENTERPRISE =
  "SET_SOURCE_COMPLETED_ENTERPRISE";

export const FETCH_AGREEMENTS_START = "FETCH_AGREEMENTS_START";
export const FETCH_AGREEMENTS_SUCCESS = "FETCH_AGREEMENTS_SUCCESS";
export const FETCH_AGREEMENTS_ERROR = "FETCH_AGREEMENTS_ERROR";

export const FETCH_PSI_START = "FETCH_PSI_START";
export const FETCH_PSI_SUCCESS = "FETCH_PSI_SUCCESS";
export const FETCH_PSI_ERROR = "FETCH_PSI_ERROR";

export const SET_SOURCES = "SET_SOURCES";

export const RESET_STORE = "RESET_STORE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_FILTERS = "SET_SEARCH_FILTERS";
export const SET_SEARCH_SORT = "SET_SEARCH_SORT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_IS_LOADING = "SET_SEARCH_IS_LOADING";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
export const RESET_SEARCH = "RESET_SEARCH";
