export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const SEARCH_TERMS = "SEARCH_TERMS";
export const SEARCH_NOMENCLATURES = "SEARCH_NOMENCLATURES";

export const SET_CURRENT_ENTERPRISE = "SET_CURRENT_ENTERPRISE";

export const RESET_STORE = "RESET_STORE";
