- name: Deploy preproduction
  hosts: fceprod
  remote_user: factory
  vars:
    ansistrano_deploy_from: /app/dist
    ansistrano_deploy_to: /home/factory/deployment
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_deploy_via: "rsync"
  roles:
    - { role: ansistrano.deploy }
  tasks:
    - name: Share .env file
      file:
        src: /home/factory/deployment/shared/dist/db.env
        dest: /home/factory/deployment/current/dist/db.env
        owner: factory
        group: factory
        state: link
    - name: Run `docker-compose build`
      shell: docker-compose build
      args:
        chdir: /home/factory/deployment/current/dist
    - name: Run `docker-compose up -d server`
      shell: docker-compose up -d server
      args:
        chdir: /home/factory/deployment/current/dist
    - name: Run migrations
      shell: docker-compose exec server ash -c "./node_modules/.bin/node-pg-migrate up --no-check-order"
      args:
        chdir: /home/factory/deployment/current/dist
    - name: Rebuild frentreprise
      shell: docker-compose exec server ash -c "cd /usr/src/app/frentreprise && npm run build"
      args:
        chdir: /home/factory/deployment/current/dist


