- name: Deploy preproduction
  hosts: all
  vars:
    ansistrano_deploy_from: /app/dist
    ansistrano_deploy_to: /home/fce/deployment
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_deploy_via: "rsync"
    ansistrano_keep_releases: 4
  roles:
    - { role: ansistrano.deploy }
  tasks:
    - name: Create deployment folder
      file:
        path: /home/fce/deployment/current/dist
        state: directory
    - name: Share .env file
      copy:
        src: /root/db.env
        dest: /home/fce/deployment/current/dist/db.env
        owner: fce
        group: fce
    - name: Run `docker-compose build`
      shell: docker-compose build
      args:
        chdir: /home/fce/deployment/current/dist
    - name: Run `docker-compose up -d server`
      shell: docker-compose up -d server
      args:
        chdir: /home/fce/deployment/current/dist
    - name: Run migrations
      shell: docker-compose exec server ash -c "./node_modules/.bin/node-pg-migrate up --no-check-order"
      args:
        chdir: /home/fce/deployment/current/dist
    - name: Rebuild frentreprise
      shell: docker-compose exec server ash -c "cd /usr/src/app/frentreprise && npm run build"
      args:
        chdir: /home/fce/deployment/current/dist




