export const API_EFFECTIF_ETP_DAY_OF_MONTH_UPDATE = 15;
export const API_EFFECTIF_ETP_SUB_MONTH_AFTER_UPDATE_DAY = 2;
export const API_EFFECTIF_ETP_SUB_MONTH_BEFORE_UPDATE_DAY = 3;

export const getSubMonthValueForApiEffectifEtp = (dayOfMonth) =>
  dayOfMonth >= API_EFFECTIF_ETP_DAY_OF_MONTH_UPDATE
    ? API_EFFECTIF_ETP_SUB_MONTH_AFTER_UPDATE_DAY
    : API_EFFECTIF_ETP_SUB_MONTH_BEFORE_UPDATE_DAY;
