front:
  ~chart: app
  ~needs: [build-front]
  imagePackage: front
  probesPath: /healthz
  containerPort: 8080
  envFrom:
    - configMapRef:
        name: client-env

server:
  ~chart: app
  ~needs: [build-server]
  imagePackage: server
  probesPath: /healthz
  containerPort: 3000
  envFrom:
    - secretRef:
        name: server-env
    - configMapRef:
        name: server-env
  env:
    - name: PG_DB
      valueFrom:
        secretKeyRef:
          key: PGDATABASE
          name: pg-app
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: pg-superuser
    - name: PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-superuser
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: pg-superuser
    - name: PG_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: pg-superuser
    - name: PG_SSL_SELF_SIGNED
      value: "true"

graphiql:
  ~chart: app
  ~needs: [build-graphiql]
  imagePackage: graphiql
  probesPath: /healthz
  containerPort: 8080

n8n:
  ~chart: app
  ~needs: [build-n8n]
  imagePackage: n8n
  probesPath: /healthz
  containerPort: 5678
  envFrom:
    - secretRef:
        name: n8n-env
    - configMapRef:
        name: n8n-env
  volumes:
    - name: downloads
  volumeMounts:
    - name: downloads
      mountPath: /tmp/download
  resources:
    requests:
      cpu: 30m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 1G
  env:
    - name: DB_POSTGRESDB_DATABASE
      valueFrom:
        secretKeyRef:
          key: PGDATABASE
          name: pg-n8n-app
    - name: DB_POSTGRESDB_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: pg-n8n-superuser
    - name: DB_POSTGRESDB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-n8n-superuser
    - name: DB_POSTGRESDB_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: pg-n8n-superuser
    - name: DB_POSTGRESDB_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: pg-n8n-superuser
    - name: PG_DATABASE
      valueFrom:
        secretKeyRef:
          key: PGDATABASE
          name: pg-app
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: pg-superuser
    - name: PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-superuser
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: pg-superuser
    - name: PG_USERNAME
      valueFrom:
        secretKeyRef:
          key: user
          name: pg-superuser

redis:
  ~chart: redis

strapi:
  ~chart: app
  ~needs: [build-strapi]
  imagePackage: strapi
  probesPath: /_health
  containerPort: 1337
  envFrom:
    - secretRef:
        name: strapi-env
    - configMapRef:
        name: strapi-env
  env:
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          key: PGDATABASE
          name: pg-strapi-app
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: pg-strapi-superuser
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pg-strapi-superuser
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: pg-strapi-superuser
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          key: user
          name: pg-strapi-superuser
    - name: DATABASE_SSL
      value: "true"

pg:
  ~chart: pg

pg-n8n:
  ~chart: pg

pg-strapi:
  ~chart: pg

jobs:
  ~chart: jobs
  runs:

    build-front:
      use: build
      with:
        imagePackage: front
        context: src/client

    build-server:
      use: build
      with:
        imagePackage: server
        context: src
        dockerfile: server/Dockerfile

    build-graphiql:
      use: build
      with:
        imagePackage: graphiql
        context: src/graphiql

    build-strapi:
      use: build
      with:
        imagePackage: strapi
        context: src/strapi

    build-n8n:
      use: build
      with:
        imagePackage: n8n
        context: src/n8n
