version: "3"

services:
  deployment:
    build: ansible
    volumes:
      - ./config/.ansible.cfg/:/root/.ansible.cfg
      - ./config/hosts:/root/hosts
      - ./config/fce-ppd.yml:/root/fce-ppd.yml
      - ./config/fce-prod.yml:/root/fce-prod.yml
      - ./config/db.env:/root/db.env
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - ../../dist:/app/dist
    tty: true
