name: Build

on:
  push:
    branches:
      - '**'

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  BuildServer:
    strategy:
      # Don't fast-fail on tag and master
      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}

    name: Building server image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          cd ./src/frentreprise
          npm install && npm run build
          cd - && cd ./src/server
          yarn --frozen-lockfile && yarn build

      - id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
        with:
          images: ghcr.io/socialgouv/fabrique/${{ env.project }}
          labels: |
            org.opencontainers.image.title=fce-server
            org.opencontainers.image.documentation=https://github.com/SocialGouv/${{ env.project }}/tree/${{ github.sha }}/fce-server
          tags: |
            type=sha
            type=raw,value=sha-${{ github.sha }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - id: docker_buildx
        name: Set up Docker Buildx
        uses: "docker/setup-buildx-action@2a4b53665e15ce7d7049afb11ff1f70ff1610609"
        with: { }

      #- if: "${{ github.event_name != 'pull_request' }}"
      - name: Login to ghcr.io/socialgouv Registry
        uses: "docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a"
        with:
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          username: "${{ github.repository_owner }}"

      - name: /tmp/.buildx-cache cache
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-fce-server-buildx-${{ hashFiles('src/server/Dockerfile') }}"
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-fce-server-buildx

      - id: docker_push
        name: Push
        uses: "docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f"
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache"
          context: "./src"
          file: "./src/server/Dockerfile"
          labels: "${{ steps.docker_meta.outputs.labels }}"
          push: 'true'
          tags: "${{ steps.docker_meta.outputs.tags }}"

      - name: Image digest
        run: |
          echo "${{ steps.docker_push.outputs.digest }}"

  BuildFront:
    strategy:
      # Don't fast-fail on tag and master
      fail-fast: ${{ github.event_name == 'pull_request' || (github.ref !=
        'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')) }}

    name: Building front image
    runs-on: ubuntu-latest

    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd ./src/client
          npm ci

      - name: Build
        run: |
          cd ./src/client
          CI=false npm run build

      - name: Build docker image
        run: |
          cd ./src/client
          docker build -t fce-client .

      - id: docker_meta
        uses: "crazy-max/ghaction-docker-meta@2e1a5c7fa42123697f82d479b551a1bbdb1bef88"
        with:
          images: ghcr.io/socialgouv/fabrique/${{ env.project }}
          labels: |
            org.opencontainers.image.title=fce-client
            org.opencontainers.image.documentation=https://github.com/SocialGouv/${{ env.project }}/tree/${{ github.sha }}/fce-client
          tags: |
            type=sha
            type=raw,value=sha-${{ github.sha }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - id: docker_buildx
        name: Set up Docker Buildx
        uses: "docker/setup-buildx-action@2a4b53665e15ce7d7049afb11ff1f70ff1610609"
        with: { }

      #- if: "${{ github.event_name != 'pull_request' }}"
      - name: Login to ghcr.io/socialgouv Registry
        uses: "docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a"
        with:
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: ghcr.io
          username: "${{ github.repository_owner }}"

      - name: /tmp/.buildx-cache cache
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-fce-client-buildx-${{ hashFiles('./src/client/Dockerfile') }}"
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-fce-client-buildx

      - id: docker_push
        name: Push
        uses: "docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f"
        with:
          builder: "${{ steps.docker_buildx.outputs.name }}"
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache"
          context: "./src/client"
          labels: "${{ steps.docker_meta.outputs.labels }}"
          push: 'true'
          tags: "${{ steps.docker_meta.outputs.tags }}"
      - name: Image digest
        run: |
          echo "${{ steps.docker_push.outputs.digest }}"

  Manifests:
    name: Generate k8s manifests for server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Load review environment variables
        run: |
          cat ".github/preprod.env" >> $GITHUB_ENV

      - name: Install k8s deps
        run: yarn k8s

      - name: Generate k8s manifests
        run: yarn -s k8s generate:dev > manifests.yml
        env:
          RANCHER_PROJECT_ID: c-gjtkk:p-8j5hf
          SOCIALGOUV_CONFIG_PATH: ${{ github.workspace }}/.socialgouv/config.json
          SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN: ${{ env.SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN }}

      - name: Generate k8s namespace
        run: yarn -s k8s generate:dev _namespace > namespace.yml
        env:
          RANCHER_PROJECT_ID: c-gjtkk:p-8j5hf
          SOCIALGOUV_CONFIG_PATH: ${{ github.workspace }}/.socialgouv/config.json
          SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN: ${{ env.SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN }}

      - name: Archive k8s manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests.yml
          path: manifests.yml

      - name: Archive k8s namespace
        uses: actions/upload-artifact@v2
        with:
          name: namespace.yml
          path: namespace.yml

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [ BuildServer, BuildFront ]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get project and namespace names
        run: |
          cat ".github/preprod.env" >> $GITHUB_ENV
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "namespace=${GITHUB_REPOSITORY#*/}-${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Download k8s manifests
        uses: actions/download-artifact@v2
        with:
          name: manifests.yml

      - name: Download k8s namespace
        uses: actions/download-artifact@v2
        with:
          name: namespace.yml

      - name: Notify deployment start
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          env: ${{ env.namespace }}
          token: ${{ secrets.GITHUB_TOKEN }}
          desc: "Deploying environment: ${{ env.namespace }}"

      - name: Install Kapp
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: kapp
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create kubernetes config
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          echo ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }} | base64 -d > ~/.kube/config

      - name: Create k8s namespace and annotations
        run: kubectl create -f namespace.yml

      - name: Deploy application
        run: kapp --dangerous-override-ownership-of-existing-resources -y deploy -a ${{ env.project }} --namespace ${{ env.namespace }} -f manifests.yml
        env:
          RANCHER_PROJECT_ID: c-gjtkk:p-8j5hf

      - name: Notify deployment end
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ env.namespace }}.${{ env.SOCIALGOUV_KUBE_INGRESS_BASE_DOMAIN }}
