- name: Deploy production
  hosts: fceprod
  remote_user: factory
  vars:
    ansistrano_deploy_from: /app/dist
    ansistrano_deploy_to: /home/factory/tools/monitoring
    ansistrano_version_dir: "releases"
    ansistrano_current_dir: "current"
    ansistrano_current_via: "symlink"
    ansistrano_deploy_via: "rsync"
  roles:
    - { role: ansistrano.deploy }
  tasks:
    - name: Share .env file
      file:
        src: /home/factory/tools/monitoring/shared/config.monitoring
        dest: /home/factory/tools/monitoring/current/dist/config.monitoring
        owner: factory
        group: factory
        state: link
    - name: Run `docker-compose build`
      shell: docker-compose build
      args:
        chdir: /home/factory/tools/monitoring/current/dist
    - name: Run `docker-compose up -d`
      shell: docker-compose up -d
      args:
        chdir: /home/factory/tools/monitoring/current/dist


